title: kma

theme: minima

layout: default

header_pages:
  - about.md
  - projects.md
  - papers.md
  - blog.md

plugins:
  - jekyll-titles-from-headings
  
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

include:
  - _projects
  - _lsa
  - _usapl
  
- scope:
    path: _projects/_lsa
   values:
    permalink: /:lsa/
