title: kma

theme: minima

layout: default

header_pages:
  - index.md
  - projects.md
  - blog.md

plugins:
  - jekyll-titles-from-headings
  
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false
